name: Build and Release PlotSquared

on:
  push:
    tags:
      - 'v*'   # runs only on version tags like v7.5.4
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # needed for creating releases

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Build shadow JARs for all modules
      run: ./gradlew shadowJar --info

    - name: Find and list all JAR files (debug)
      run: find . -type f -name "*.jar" -exec ls -lh {} \;

    - name: Upload plotsquared-bukkit fat JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: plotsquared-fat-jar
        path: |
          plotsquared-bukkit/build/libs/*.jar
          !plotsquared-bukkit/build/libs/*-sources.jar
          !plotsquared-bukkit/build/libs/*-javadoc.jar

    - name: Create GitHub Release with fat JAR
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: PlotSquared ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: |
          plotsquared-bukkit/build/libs/*.jar
          !plotsquared-bukkit/build/libs/*-sources.jar
          !plotsquared-bukkit/build/libs/*-javadoc.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
