name: Build and Upload JAR

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build shadow JAR
      run: ./gradlew :plotsquared-bukkit:shadowJar

    - name: Show built JARs
      run: ls -lh plotsquared-bukkit/build/libs

    - name: Upload fat JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: plotsquared-fat-jar
        path: "plotsquared-bukkit/build/libs/plotsquared-bukkit-*.jar"
