name: Build and Release PlotSquared

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Optional release tag for manual runs (e.g., v7.5.4)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle (shadowJar)
        run: ./gradlew :plotsquared-bukkit:shadowJar

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: plotsquared-bukkit
          path: |
            plotsquared-bukkit/build/libs/*.jar
            !plotsquared-bukkit/build/libs/*-sources.jar
            !plotsquared-bukkit/build/libs/*-javadoc.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: plotsquared-bukkit
          path: release-files

      - name: Show files
        run: ls -lh release-files

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name || github.event.inputs.release_tag }}
          files: release-files/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
