name: Build and Release PlotSquared

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v7.5.4

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build shadow JAR
      run: ./gradlew :plotsquared-bukkit:shadowJar

    - name: List JARs
      run: ls -lh plotsquared-bukkit/build/libs

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: plotsquared-fat-jar
        path: |
          plotsquared-bukkit/build/libs/*.jar
          !plotsquared-bukkit/build/libs/*-sources.jar
          !plotsquared-bukkit/build/libs/*-javadoc.jar

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: PlotSquared ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: |
          plotsquared-bukkit/build/libs/*.jar
          !plotsquared-bukkit/build/libs/*-sources.jar
          !plotsquared-bukkit/build/libs/*-javadoc.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
